version: 2.1
orbs:
  node: circleci/node@5.0.2
##
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: build packages
          command: |
            npm run build
  #
  test:
    docker:
      - image: "cimg/base:stable"
      - image: cimg/postgres:15.0.0
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: build packages
          command: |
            npm run build
      - run:
          name: start database
          command: npm run db
      - run:
          name: run migrations
          command: npm run migrations
      - run:
          name: run tests
          command: npm run test
  #
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Deploy to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
##
workflows:
  build and deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
